apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetest
  template:
    metadata:
      labels:
        app: kubetest
    spec:
      containers:
      - name: nodeapp
        imagePullPolicy: Always
        image: sanatchoubey/internalproject:5
        ports:
        - containerPort: 8000
        env:
          - name: dataurl
            value: "dataservice.default:9000"

#  imagePullSecrets:
        # - name: myregistry.com-registry-key